<?php

namespace Database\Seeders;

use App\Models\TravelPolicy;
use Illuminate\Database\Seeder;

class TravelPolicySeeder extends Seeder
{
    public function run(): void
    {
        $policies = [
            // Executive Level Policies
            [
                'policy_name' => 'Executive International Travel',
                'description' => 'International travel policy for executive level employees with business class flights and premium accommodations',
                'travel_type' => 'international',
                'designation_level' => 'executive',
                'max_flight_cost' => 300000.00,
                'max_hotel_per_night' => 30000.00,
                'per_diem_rate' => 15000.00,
                'mileage_rate_per_km' => 25.00,
                'advance_allowed' => true,
                'max_advance_percentage' => 80.00,
                'advance_days_before_travel' => 7,
                'settlement_days_after_return' => 15,
                'requires_manager_approval' => false,
                'requires_finance_approval' => true,
                'finance_approval_threshold' => 500000.00,
                'is_active' => true,
            ],
            [
                'policy_name' => 'Executive Domestic Travel',
                'description' => 'Domestic travel policy for executive level employees',
                'travel_type' => 'domestic',
                'designation_level' => 'executive',
                'max_flight_cost' => 100000.00,
                'max_hotel_per_night' => 15000.00,
                'per_diem_rate' => 5000.00,
                'mileage_rate_per_km' => 25.00,
                'advance_allowed' => true,
                'max_advance_percentage' => 75.00,
                'advance_days_before_travel' => 5,
                'settlement_days_after_return' => 10,
                'requires_manager_approval' => false,
                'requires_finance_approval' => false,
                'finance_approval_threshold' => 200000.00,
                'is_active' => true,
            ],
            
            // Senior Management Policies
            [
                'policy_name' => 'Senior Management International Travel',
                'description' => 'International travel policy for senior management',
                'travel_type' => 'international',
                'designation_level' => 'senior',
                'max_flight_cost' => 200000.00,
                'max_hotel_per_night' => 20000.00,
                'per_diem_rate' => 10000.00,
                'mileage_rate_per_km' => 20.00,
                'advance_allowed' => true,
                'max_advance_percentage' => 75.00,
                'advance_days_before_travel' => 7,
                'settlement_days_after_return' => 15,
                'requires_manager_approval' => true,
                'requires_finance_approval' => true,
                'finance_approval_threshold' => 300000.00,
                'is_active' => true,
            ],
            [
                'policy_name' => 'Senior Management Domestic Travel',
                'description' => 'Domestic travel policy for senior management',
                'travel_type' => 'domestic',
                'designation_level' => 'senior',
                'max_flight_cost' => 60000.00,
                'max_hotel_per_night' => 10000.00,
                'per_diem_rate' => 3500.00,
                'mileage_rate_per_km' => 20.00,
                'advance_allowed' => true,
                'max_advance_percentage' => 70.00,
                'advance_days_before_travel' => 5,
                'settlement_days_after_return' => 10,
                'requires_manager_approval' => true,
                'requires_finance_approval' => false,
                'finance_approval_threshold' => 150000.00,
                'is_active' => true,
            ],
            
            // Middle Management Policies
            [
                'policy_name' => 'Mid-Level Management International Travel',
                'description' => 'International travel policy for mid-level management',
                'travel_type' => 'international',
                'designation_level' => 'mid',
                'max_flight_cost' => 150000.00,
                'max_hotel_per_night' => 15000.00,
                'per_diem_rate' => 7000.00,
                'mileage_rate_per_km' => 18.00,
                'advance_allowed' => true,
                'max_advance_percentage' => 70.00,
                'advance_days_before_travel' => 10,
                'settlement_days_after_return' => 15,
                'requires_manager_approval' => true,
                'requires_finance_approval' => true,
                'finance_approval_threshold' => 200000.00,
                'is_active' => true,
            ],
            [
                'policy_name' => 'Mid-Level Management Domestic Travel',
                'description' => 'Domestic travel policy for mid-level management',
                'travel_type' => 'domestic',
                'designation_level' => 'mid',
                'max_flight_cost' => 45000.00,
                'max_hotel_per_night' => 7000.00,
                'per_diem_rate' => 2500.00,
                'mileage_rate_per_km' => 18.00,
                'advance_allowed' => true,
                'max_advance_percentage' => 65.00,
                'advance_days_before_travel' => 7,
                'settlement_days_after_return' => 10,
                'requires_manager_approval' => true,
                'requires_finance_approval' => false,
                'finance_approval_threshold' => 100000.00,
                'is_active' => true,
            ],
            
            // Junior Staff Policies
            [
                'policy_name' => 'Junior Staff International Travel',
                'description' => 'International travel policy for junior staff',
                'travel_type' => 'international',
                'designation_level' => 'junior',
                'max_flight_cost' => 100000.00,
                'max_hotel_per_night' => 10000.00,
                'per_diem_rate' => 5000.00,
                'mileage_rate_per_km' => 15.00,
                'advance_allowed' => true,
                'max_advance_percentage' => 65.00,
                'advance_days_before_travel' => 14,
                'settlement_days_after_return' => 15,
                'requires_manager_approval' => true,
                'requires_finance_approval' => true,
                'finance_approval_threshold' => 150000.00,
                'is_active' => true,
            ],
            [
                'policy_name' => 'Junior Staff Domestic Travel',
                'description' => 'Domestic travel policy for junior staff',
                'travel_type' => 'domestic',
                'designation_level' => 'junior',
                'max_flight_cost' => 30000.00,
                'max_hotel_per_night' => 5000.00,
                'per_diem_rate' => 1800.00,
                'mileage_rate_per_km' => 15.00,
                'advance_allowed' => true,
                'max_advance_percentage' => 60.00,
                'advance_days_before_travel' => 10,
                'settlement_days_after_return' => 10,
                'requires_manager_approval' => true,
                'requires_finance_approval' => false,
                'finance_approval_threshold' => 75000.00,
                'is_active' => true,
            ],
            
            // General/All Level Policies
            [
                'policy_name' => 'General International Travel',
                'description' => 'Default international travel policy for all employees',
                'travel_type' => 'international',
                'designation_level' => 'all',
                'max_flight_cost' => 120000.00,
                'max_hotel_per_night' => 12000.00,
                'per_diem_rate' => 6000.00,
                'mileage_rate_per_km' => 15.00,
                'advance_allowed' => true,
                'max_advance_percentage' => 70.00,
                'advance_days_before_travel' => 10,
                'settlement_days_after_return' => 15,
                'requires_manager_approval' => true,
                'requires_finance_approval' => false,
                'finance_approval_threshold' => 200000.00,
                'is_active' => true,
            ],
            [
                'policy_name' => 'General Domestic Travel',
                'description' => 'Default domestic travel policy for all employees',
                'travel_type' => 'domestic',
                'designation_level' => 'all',
                'max_flight_cost' => 40000.00,
                'max_hotel_per_night' => 6000.00,
                'per_diem_rate' => 2000.00,
                'mileage_rate_per_km' => 15.00,
                'advance_allowed' => true,
                'max_advance_percentage' => 65.00,
                'advance_days_before_travel' => 7,
                'settlement_days_after_return' => 10,
                'requires_manager_approval' => true,
                'requires_finance_approval' => false,
                'finance_approval_threshold' => 100000.00,
                'is_active' => true,
            ],
        ];

        foreach ($policies as $policy) {
            TravelPolicy::create($policy);
        }
    }
}
